import { nanoid } from 'nanoid'

export interface IExerciseDetails {
  id: string
  name: string
  difficulty: string
  targetMuscles: string
  description: string
  firstExerciseImage: string
  secondExerciseImage: string
  equipmentCategory: 'none' | 'bodyweight' | 'dumbbells' | 'barbell' | 'band'
  bodyPartCategory:
    | 'none'
    | 'abdominals'
    | 'chest'
    | 'triceps'
    | 'biceps'
    | 'lats'
    | 'shoulders'
    | 'lowerback'
    | 'quads'
    | 'hamstrings'
    | 'glutes'
    | 'calves'
}

export const exercises: IExerciseDetails[] = [
  {
    id: nanoid(),
    name: 'Скручивания',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Пресс (10/10)',
    description: 'Изолирующее упражнение, направленное на развитие или функциональное поддержание прямой мышцы живота.',
    firstExerciseImage: '/exercises/bodyweight/Crunches1.webp',
    secondExerciseImage: '/exercises/bodyweight/Crunches2.webp',
    equipmentCategory: 'bodyweight',
    bodyPartCategory: 'abdominals',
  },
  {
    id: nanoid(),
    name: 'Подъём ног, лёжа на полу',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Пресс (9/10)',
    description: 'Изолирующее упражнение, направленное на развитие или функциональное поддержание прямой мышцы живота.',
    firstExerciseImage: '/exercises/bodyweight/LayingLegRaises1.webp',
    secondExerciseImage: '/exercises/bodyweight/LayingLegRaises2.webp',
    equipmentCategory: 'bodyweight',
    bodyPartCategory: 'abdominals',
  },
  {
    id: nanoid(),
    name: 'Подъём колен в висе',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Пресс (8/10), подвздошно-поясничная мышца (8/10), предплечья (3/10)',
    description:
      'Упражнение в первую очередь предназначено для развития прямой мышцы живота, но также задействует подвздошно-поясничную мышцу и мышцы предплечья',
    firstExerciseImage: '/exercises/bodyweight/HangingKneeRaises1.webp',
    secondExerciseImage: '/exercises/bodyweight/HangingKneeRaises2.webp',
    equipmentCategory: 'bodyweight',
    bodyPartCategory: 'abdominals',
  },
  {
    id: nanoid(),
    name: 'Планка',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Пресс (7/10), мышцы-разгибатели спины (5/10), подвздошная-поясничная мышца (3/10), ягодицы (1/10)',
    description:
      'Упражнение направлено для статического напряжения мышц кора. Приводит к более качественному развитию указанных мышечнух групп в сочетании с динамическими упражнениями.',
    firstExerciseImage: '/exercises/bodyweight/Plank1.webp',
    secondExerciseImage: '/exercises/bodyweight/Plank2.webp',
    equipmentCategory: 'bodyweight',
    bodyPartCategory: 'abdominals',
  },
  {
    id: nanoid(),
    name: 'Отжимания',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Грудь (10/10), трицепс (6/10), передняя дельта (3/10)',
    description:
      'Упражнение нацелено на проработку мышц груди, но в том числе в этом упражнении задействованы и другие, сопутствующие мышечные группы.',
    firstExerciseImage: '/exercises/bodyweight/PushUps1.webp',
    secondExerciseImage: '/exercises/bodyweight/PushUps2.webp',
    equipmentCategory: 'bodyweight',
    bodyPartCategory: 'chest',
  },
  {
    id: nanoid(),
    name: 'Отжимания от брусьев (на грудь)',
    difficulty: 'Средняя сложность',
    targetMuscles: 'Грудь (10/10), трицепс (10/10), передняя дельта (3/10)',
    description:
      'Упражнение нацелено на проработку в первую очередь грудных мышц и трицепса, в зависимости от техники выполнения.',
    firstExerciseImage: '/exercises/bodyweight/Dips1.webp',
    secondExerciseImage: '/exercises/bodyweight/Dips2.webp',
    equipmentCategory: 'bodyweight',
    bodyPartCategory: 'chest',
  },
  {
    id: nanoid(),
    name: 'Отжимания узким хватом',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Трицепс (10/10), грудь (6/10), передняя дельта (3/10)',
    description:
      'Упражнение нацелено на проработку трицепса, но целевая мышечная группа варьируется в зависимости от техники выполнения и собственных ощущений.',
    firstExerciseImage: '/exercises/bodyweight/DiamondPushUps1.webp',
    secondExerciseImage: '/exercises/bodyweight/DiamondPushUps2.webp',
    equipmentCategory: 'bodyweight',
    bodyPartCategory: 'triceps',
  },
  {
    id: nanoid(),
    name: 'Отжимания от скамьи',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Трицепс (9/10), грудь (5/10), передняя дельта (4/10)',
    description: 'Упражнение нацелено на проработку трицепса, но также задействует мышцы груди и передней дельты',
    firstExerciseImage: '/exercises/bodyweight/BenchDips1.webp',
    secondExerciseImage: '/exercises/bodyweight/BenchDips2.webp',
    equipmentCategory: 'bodyweight',
    bodyPartCategory: 'triceps',
  },
  {
    id: nanoid(),
    name: 'Отжимания от брусьев (на трицепс)',
    difficulty: 'Средняя сложность',
    targetMuscles: 'Трицепс (10/10), грудь (10/10), передняя дельта (3/10)',
    description:
      'Упражнение нацелено на проработку в первую очередь мышц трицепса и груди, в зависимости от техники выполнения.',
    firstExerciseImage: '/exercises/bodyweight/TricepsDips1.webp',
    secondExerciseImage: '/exercises/bodyweight/TricepsDips2.webp',
    equipmentCategory: 'bodyweight',
    bodyPartCategory: 'triceps',
  },
  {
    id: nanoid(),
    name: 'Подтягивания обратным хватом',
    difficulty: 'Средняя сложность',
    targetMuscles:
      'Бицепс (10/10), широчайшая мышца (8/10), предплечья (5/10), низ трапеции (3/10), задняя дельта (1/10)',
    description: 'Упражнение нацелено на проработку множества мышечных групп на руках и спине',
    firstExerciseImage: '/exercises/bodyweight/ChinUps1.webp',
    secondExerciseImage: '/exercises/bodyweight/ChinUps2.webp',
    equipmentCategory: 'bodyweight',
    bodyPartCategory: 'biceps',
  },
  {
    id: nanoid(),
    name: 'Австралийские подтягивания',
    difficulty: 'Начальная сложность',
    targetMuscles:
      'Широчайшие мышцы (8/10), низ трапеции (7/10), предплечья (5/10), задняя дельта (4/10), бицепс (4/10)',
    description: 'Упражнение нацелено на проработку множества мышечных групп на спине и руках',
    firstExerciseImage: '/exercises/bodyweight/InvertedRow1.webp',
    secondExerciseImage: '/exercises/bodyweight/InvertedRow2.webp',
    equipmentCategory: 'bodyweight',
    bodyPartCategory: 'lats',
  },
  {
    id: nanoid(),
    name: 'Подтягивания',
    difficulty: 'Средняя сложность',
    targetMuscles:
      'Широчайшие мышцы (9/10), низ трапеций (6/10), предплечья (5/10), задняя дельта (4/10), бицепс (4/10)',
    description:
      'Упражнение нацелено на проработку спины в первую очередь (широчайших мышц, низа трапеции), но также задействует и мышцы рук (бицепс, предплечья). Нагрузка, как и везде, зависит от техники выполнения.',
    firstExerciseImage: '/exercises/bodyweight/PullUps1.webp',
    secondExerciseImage: '/exercises/bodyweight/PullUps2.webp',
    equipmentCategory: 'bodyweight',
    bodyPartCategory: 'lats',
  },
  {
    id: nanoid(),
    name: 'Отжимания вниз головой',
    difficulty: 'Средняя сложность',
    targetMuscles: 'Средняя дельта (7/10), передняя дельта (6/10), трицепс (4/10)',
    description: 'Упражнение нацелено на проработку передней и средней дельты',
    firstExerciseImage: '/exercises/bodyweight/ElevatedPikePress1.webp',
    secondExerciseImage: '/exercises/bodyweight/ElevatedPikePress2.webp',
    equipmentCategory: 'bodyweight',
    bodyPartCategory: 'shoulders',
  },
  {
    id: nanoid(),
    name: 'С добрым утром',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Низ спины (10/10), задняя поверхность бедра (6/10), ягодицы (5/10)',
    description: 'Упражнение нацелено на укрепление мышц-разгибателей спины.',
    firstExerciseImage: '/exercises/bodyweight/GoodMorning1.webp',
    secondExerciseImage: '/exercises/bodyweight/GoodMorning2.webp',
    equipmentCategory: 'bodyweight',
    bodyPartCategory: 'lowerback',
  },
  {
    id: nanoid(),
    name: 'Супермэн',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Низ спины (10/10)',
    description: 'Упражнение нацелено на укрепление мышц-разгибателей спины.',
    firstExerciseImage: '/exercises/bodyweight/Superman1.webp',
    secondExerciseImage: '/exercises/bodyweight/Superman2.webp',
    equipmentCategory: 'bodyweight',
    bodyPartCategory: 'lowerback',
  },
  {
    id: nanoid(),
    name: 'Приседания',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Квадрицепс (8/10), ягодицы (7/10), задняя поверхность бедра (5/10)',
    description: 'Упражнение нацелено на укрепление квадрицепса.',
    firstExerciseImage: '/exercises/bodyweight/Squats1.webp',
    secondExerciseImage: '/exercises/bodyweight/Squats2.webp',
    equipmentCategory: 'bodyweight',
    bodyPartCategory: 'quads',
  },
  {
    id: nanoid(),
    name: 'Выпады вперёд',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Квадрицепс (9/10), задняя поверхность бедра (7/10), ягодицы (6/10)',
    description: 'Упражнение нацелено на укрепление квадрицепса.',
    firstExerciseImage: '/exercises/bodyweight/ForwardLunges1.webp',
    secondExerciseImage: '/exercises/bodyweight/ForwardLunges2.webp',
    equipmentCategory: 'bodyweight',
    bodyPartCategory: 'quads',
  },
  {
    id: nanoid(),
    name: 'Болгарские приседания',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Квадрицепс (10/10), ягодицы (8/10)',
    description: 'Упражнение нацелено на проработку и развитие мышц квадрицепса.',
    firstExerciseImage: '/exercises/bodyweight/BulgarianSplitSquats1.webp',
    secondExerciseImage: '/exercises/bodyweight/BulgarianSplitSquats2.webp',
    equipmentCategory: 'bodyweight',
    bodyPartCategory: 'quads',
  },
  {
    id: nanoid(),
    name: 'Приседания с подпрыгиванием',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Квадрицепс (9/10), ягодицы (6/10)',
    description: 'Упражнение нацелено на проработку и развитие мышц квадрицепса.',
    firstExerciseImage: '/exercises/bodyweight/JumpSquats1.webp',
    secondExerciseImage: '/exercises/bodyweight/JumpSquats2.webp',
    equipmentCategory: 'bodyweight',
    bodyPartCategory: 'quads',
  },
  {
    id: nanoid(),
    name: 'Выпады в сторону',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Квадрицепс (7/10), ягодицы (5/10)',
    description: 'Упражнение нацелено на укрепление и развитие мышц квадрицепса.',
    firstExerciseImage: '/exercises/bodyweight/SideLunges1.webp',
    secondExerciseImage: '/exercises/bodyweight/SideLunges2.webp',
    equipmentCategory: 'bodyweight',
    bodyPartCategory: 'quads',
  },
  {
    id: nanoid(),
    name: 'Диагональные выпады',
    difficulty: 'Средняя сложность',
    targetMuscles: 'Квадрицепс (10/10), ягодицы (7/10)',
    description: 'Упражнение нацелено на укрепление и развитие мышц квадрицепса.',
    firstExerciseImage: '/exercises/bodyweight/ReverseLunges1.webp',
    secondExerciseImage: '/exercises/bodyweight/ReverseLunges2.webp',
    equipmentCategory: 'bodyweight',
    bodyPartCategory: 'quads',
  },
  {
    id: nanoid(),
    name: 'Выпады назад',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Квадрицепс (8/10), задняя поверхность бедра (6/10), ягодицы (4/10)',
    description: 'Упражнение нацелено на общее укрепление мышц ног (задней поверхности бедра и квадрицепса)',
    firstExerciseImage: '/exercises/bodyweight/ReversedLunge1.webp',
    secondExerciseImage: '/exercises/bodyweight/ReversedLunge2.webp',
    equipmentCategory: 'bodyweight',
    bodyPartCategory: 'quads',
  },
  {
    id: nanoid(),
    name: 'Отведение бедра назад',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Задняя поверхность бедра (10/10)',
    description: 'Упражнение нацелено на укрепление задней поверхности бедра.',
    firstExerciseImage: '/exercises/bodyweight/Kickbacks1.webp',
    secondExerciseImage: '/exercises/bodyweight/Kickbacks2.webp',
    equipmentCategory: 'bodyweight',
    bodyPartCategory: 'hamstrings',
  },
  {
    id: nanoid(),
    name: 'Скандинавские сгибания бедра',
    difficulty: 'Продвинутая сложность',
    targetMuscles: 'Задняя поверхность бедра (10/10)',
    description:
      'Упражнение нацелено на развитие задней поверхности бедра. Требует фиксации ног для правильного выполнения.',
    firstExerciseImage: '/exercises/bodyweight/NordicHamstringCurl1.webp',
    secondExerciseImage: '/exercises/bodyweight/NordicHamstringCurl2.webp',
    equipmentCategory: 'bodyweight',
    bodyPartCategory: 'hamstrings',
  },
  {
    id: nanoid(),
    name: 'Ягодичный мостик',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Ягодицы (10/10), задняя поверхность бедра (6/10)',
    description: 'Упражнение направлено на развитие мышц ягодиц.',
    firstExerciseImage: '/exercises/bodyweight/GluteBridge1.webp',
    secondExerciseImage: '/exercises/bodyweight/GluteBridge2.webp',
    equipmentCategory: 'bodyweight',
    bodyPartCategory: 'glutes',
  },
  {
    id: nanoid(),
    name: 'Приседания',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Квадрицепс (8/10), ягодицы (7/10), задняя поверхность бедра (5/10)',
    description: 'Упражнение нацелено на укрепление квадрицепса.',
    firstExerciseImage: '/exercises/bodyweight/Squats1.webp',
    secondExerciseImage: '/exercises/bodyweight/Squats1.webp',
    equipmentCategory: 'bodyweight',
    bodyPartCategory: 'glutes',
  },
  {
    id: nanoid(),
    name: 'Выпады вперёд',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Квадрицепс (9/10), задняя поверхность бедра (7/10), ягодицы (6/10)',
    description: 'Упражнение нацелено на укрепление квадрицепса.',
    firstExerciseImage: '/exercises/bodyweight/ForwardLunges1.webp',
    secondExerciseImage: '/exercises/bodyweight/ForwardLunges2.webp',
    equipmentCategory: 'bodyweight',
    bodyPartCategory: 'glutes',
  },
  {
    id: nanoid(),
    name: 'Болгарские приседания',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Квадрицепс (10/10), ягодицы (8/10)',
    description: 'Упражнение нацелено на проработку и развитие мышц квадрицепса.',
    firstExerciseImage: '/exercises/bodyweight/BulgarianSplitSquats1.webp',
    secondExerciseImage: '/exercises/bodyweight/BulgarianSplitSquats1.webp',
    equipmentCategory: 'bodyweight',
    bodyPartCategory: 'glutes',
  },
  {
    id: nanoid(),
    name: 'Приседания с подпрыгиванием',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Квадрицепс (9/10), ягодицы (6/10)',
    description: 'Упражнение нацелено на проработку и развитие мышц квадрицепса.',
    firstExerciseImage: '/exercises/bodyweight/JumpSquats1.webp',
    secondExerciseImage: '/exercises/bodyweight/JumpSquats2.webp',
    equipmentCategory: 'bodyweight',
    bodyPartCategory: 'glutes',
  },
  {
    id: nanoid(),
    name: 'Выпады в сторону',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Квадрицепс (7/10), ягодицы (5/10)',
    description: 'Упражнение нацелено на укрепление и развитие мышц квадрицепса.',
    firstExerciseImage: '/exercises/bodyweight/SideLunges1.webp',
    secondExerciseImage: '/exercises/bodyweight/SideLunges2.webp',
    equipmentCategory: 'bodyweight',
    bodyPartCategory: 'glutes',
  },
  {
    id: nanoid(),
    name: 'Диагональные выпады',
    difficulty: 'Средняя сложность',
    targetMuscles: 'Квадрицепс (10/10), ягодицы (7/10)',
    description: 'Упражнение нацелено на укрепление и развитие мышц квадрицепса.',
    firstExerciseImage: '/exercises/bodyweight/ReverseLunges1.webp',
    secondExerciseImage: '/exercises/bodyweight/ReverseLunges2.webp',
    equipmentCategory: 'bodyweight',
    bodyPartCategory: 'glutes',
  },
  {
    id: nanoid(),
    name: 'Выпады назад',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Квадрицепс (8/10), задняя поверхность бедра (6/10), ягодицы (4/10)',
    description: 'Упражнение нацелено на общее укрепление мышц ног (задней поверхности бедра и квадрицепса)',
    firstExerciseImage: '/exercises/bodyweight/ReversedLunge1.webp',
    secondExerciseImage: '/exercises/bodyweight/ReversedLunge2.webp',
    equipmentCategory: 'bodyweight',
    bodyPartCategory: 'glutes',
  },
  {
    id: nanoid(),
    name: 'Ходьба на носках',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Икроножные (7/10)',
    description: 'Упражнение направлено на укрепление икроножных мышц.',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'bodyweight',
    bodyPartCategory: 'calves',
  },
  {
    id: nanoid(),
    name: 'Подъёмы на носках',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Икроножные (7/10)',
    description: 'Упражнение направлено на укрепление икроножных мышц.',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'bodyweight',
    bodyPartCategory: 'calves',
  },
  {
    id: nanoid(),
    name: 'Подъёмы с гантелей',
    difficulty: 'Средняя сложность',
    targetMuscles: 'Пресс (10/10)',
    description: 'Упражнение нацелено на проработку мышц брюшного пресса.',
    firstExerciseImage: '/exercises/dumbbells/DumbbellSitups1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellSitups2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'abdominals',
  },
  {
    id: nanoid(),
    name: 'Скручивания с гантелей',
    difficulty: 'Средняя сложность',
    targetMuscles: 'Пресс (10/10)',
    description: 'Упражнение нацелено на проработку и развитие мышц брюшного пресса.',
    firstExerciseImage: '/exercises/dumbbells/DumbbellCrunches1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellCrunches2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'chest',
  },
  {
    id: nanoid(),
    name: 'Жим гантелей на скамье',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Грудь (10/10), передняя дельта (7/10)',
    description:
      'Упражнение нацелено на проработку мышц груди, также задействуется передняя дельта и мышцы-стабилизаторы.',
    firstExerciseImage: '/exercises/dumbbells/BenchPress1.webp',
    secondExerciseImage: '/exercises/dumbbells/BenchPress2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'chest',
  },
  {
    id: nanoid(),
    name: 'Жим гантелей под углом 45° на скамье',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Верх груди/грудь (10/10), передняя дельта (3/10)',
    description:
      'Упражнение нацелено на проработку верхней части мышц груди, также незначительно задействуется передняя дельта и мышцы-стабилизаторы.',
    firstExerciseImage: '/exercises/dumbbells/InclineBenchPress1.webp',
    secondExerciseImage: '/exercises/dumbbells/InclineBenchPress2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'chest',
  },
  {
    id: nanoid(),
    name: 'Жим гантелей под отрицательным углом на скамье',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Низ груди/грудь (10/10), передняя дельта (3/10)',
    description: 'Упражнение нацелено на растяжку и развитие нижней части грудных мышц.',
    firstExerciseImage: '/exercises/dumbbells/DeclineBenchPress1.webp',
    secondExerciseImage: '/exercises/dumbbells/DeclineBenchPress2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'chest',
  },
  {
    id: nanoid(),
    name: 'Разведение гантелей на скамье',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Грудь (10/10), передняя дельта (6/10)',
    description: 'Упражнение нацелено на растяжку и развитие грудных мышц.',
    firstExerciseImage: '/exercises/dumbbells/DumbbellChestFly1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellChestFly2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'chest',
  },
  {
    id: nanoid(),
    name: 'Разведение гантелей под углом 45° на скамье',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Верх груди/грудь (10/10), передняя дельта (3/10)',
    description: 'Упражнение нацелено на растяжку и развитие верхней части грудных мышц.',
    firstExerciseImage: '/exercises/dumbbells/DumbbellDeclineChestFly1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellDeclineChestFly2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'chest',
  },
  {
    id: nanoid(),
    name: 'Разведение гантелей под отрицательным углом на скамье',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Низ груди/грудь (10/10), передняя дельта (3/10)',
    description: 'Упражнение нацелено на растяжку и развитие нижней части грудных мышц.',
    firstExerciseImage: '/exercises/dumbbells/DumbbellInclineChestFly1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellInclineChestFly2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'chest',
  },
  {
    id: nanoid(),
    name: 'Жим объединённых гантелей по центру',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Грудь (10/10), передняя дельта (3/10)',
    description: 'Упражнение нацелено на развитие грудных мышц.',
    firstExerciseImage: '/exercises/dumbbells/DumbbellSqueezePress1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellSqueezePress2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'chest',
  },
  {
    id: nanoid(),
    name: 'Разгибания лёжа на скамье / "Крушитель черепов"',
    difficulty: 'Средняя сложность',
    targetMuscles: 'Трицепс (10/10)',
    description: 'Упражнение нацелено на проработку трицепса.',
    firstExerciseImage: '/exercises/dumbbells/DumbbellSkullcrusher1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellSkullcrusher2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'triceps',
  },
  {
    id: nanoid(),
    name: 'Французский жим одной гантели сидя или стоя',
    difficulty: 'Средняя сложность',
    targetMuscles: 'Трицепс (10/10)',
    description: 'Упражнение нацелено на проработку трицепса.',
    firstExerciseImage: '/exercises/dumbbells/DumbbellSeatedOverheadTricepsExtension1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellSeatedOverheadTricepsExtension2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'triceps',
  },
  {
    id: nanoid(),
    name: 'Французский жим одной гантели сидя под углом 45°',
    difficulty: 'Средняя сложность',
    targetMuscles: 'Трицепс (10/10)',
    description: 'Упражнение нацелено на проработку трицепса.',
    firstExerciseImage: '/exercises/dumbbells/DumbbellInclineSeatedOverheadTricepsExtension1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellInclineSeatedOverheadTricepsExtension2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'triceps',
  },
  {
    id: nanoid(),
    name: 'Французский жим по одной руке гантелями сидя или стоя',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Трицепс (10/10)',
    description: 'Упражнение нацелено на проработку трицепса.',
    firstExerciseImage: '/exercises/dumbbells/DumbbellSingleArmOverheadTricepsExtension1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellSingleArmOverheadTricepsExtension2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'triceps',
  },
  {
    id: nanoid(),
    name: 'Разгибания стоя в наклоне / Кикбэки',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Трицепс (10/10)',
    description:
      'Упражнение нацелено на растяжку и конечную проработку трицепса. Обычно добавляется в конец тренировки на трицепс.',
    firstExerciseImage: '/exercises/dumbbells/DumbbellTricepsKickback1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellTricepsKickback2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'triceps',
  },
  {
    id: nanoid(),
    name: 'Разгибания гантели лёжа по одной руке',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Трицепс (10/10)',
    description: 'Упражнение нацелено на растяжку и конечную проработку трицепса.',
    firstExerciseImage: '/exercises/dumbbells/DumbbellSingleArmPress1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellSingleArmPress2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'triceps',
  },
  {
    id: nanoid(),
    name: 'Супинированные сгибания гантелей',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Бицепс (10/10)',
    description: 'Упражнение нацелено на проработку бицепса.',
    firstExerciseImage: '/exercises/dumbbells/DumbbellCurl1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellCurl2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'biceps',
  },
  {
    id: nanoid(),
    name: 'Молотки',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Бицепс (10/10), предплечье (6/10)',
    description: 'Упражнение нацелено на проработку брахиалиса, мышц предплечья и бицепса.',
    firstExerciseImage: '/exercises/dumbbells/Hammers1.webp',
    secondExerciseImage: '/exercises/dumbbells/Hammers2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'biceps',
  },
  {
    id: nanoid(),
    name: 'Пронированные сгибания гантелей',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Предплечье (8/10), бицепс (5/10)',
    description: 'Упражнение нацелено на проработку мышц предплечья и бицепса.',
    firstExerciseImage: '/exercises/dumbbells/DumbbellReverseCurls1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellReverseCurls2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'biceps',
  },
  {
    id: nanoid(),
    name: 'Сгибания, лёжа под углом под углом 45° / Паучьи сгибания',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Бицепс (10/10)',
    description: 'Упражнение нацелено на проработку мышц бицепса.',
    firstExerciseImage: '/exercises/dumbbells/SpiderCurls1.webp',
    secondExerciseImage: '/exercises/dumbbells/SpiderCurls2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'biceps',
  },
  {
    id: nanoid(),
    name: 'Концентрированные сгибания стоя',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Бицепс (10/10)',
    description: 'Упражнение нацелено на проработку верхней головки бицепса.',
    firstExerciseImage: '/exercises/dumbbells/StandingConcentrationCurls1.webp',
    secondExerciseImage: '/exercises/dumbbells/StandingConcentrationCurls2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'biceps',
  },
  {
    id: nanoid(),
    name: 'Тяга гантелей в наклоне',
    difficulty: 'Средняя сложность',
    targetMuscles: 'Широчайшие мышцы (10/10), низ трапеций (5/10)',
    description: 'Упражнение нацелено на проработку широчайших мышц спины.',
    firstExerciseImage: '/exercises/dumbbells/DumbbellRow1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellRow2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'lats',
  },
  {
    id: nanoid(),
    name: 'Тяга одной гантели в наклоне',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Широчайшие мышцы (10/10), низ трапеций (5/10)',
    description: 'Упражнение нацелено на детальную проработку широчайших мышц спины.',
    firstExerciseImage: '/exercises/dumbbells/DumbbellUnilateralRow1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellUnilateralRow2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'lats',
  },
  {
    id: nanoid(),
    name: 'Тяга гантелей лёжа на наклонной скамье',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Широчайшие мышцы (10/10)',
    description: 'Упражнение нацелено на проработку широчайших мышц спины.',
    firstExerciseImage: '/exercises/dumbbells/DumbbellBenchRow1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellBenchRow2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'lats',
  },
  {
    id: nanoid(),
    name: 'Пуловер с гантелью',
    difficulty: 'Средняя сложность',
    targetMuscles: 'Широчайшие мышцы (8/10), грудь (7/10)',
    description: 'Упражнение нацелено на растягивание широчайших мышц спины и мышц груди.',
    firstExerciseImage: '/exercises/dumbbells/DumbbellPullover1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellPullover2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'lats',
  },
  {
    id: nanoid(),
    name: 'Жим гантелей стоя или сидя',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Средняя дельта (8/10), передняя дельта (7/10), задняя дельта (4/10), трицепс (2/10)',
    description: 'Упражнение нацелено на проработку дельтовидных мышц.',
    firstExerciseImage: '/exercises/dumbbells/DumbbellOverheadPress1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellOverheadPress2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'shoulders',
  },
  {
    id: nanoid(),
    name: 'Разведение гантелей',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Средняя дельта (8/10), передняя дельта (8/10), задняя дельта (2/10)',
    description: 'Упражнение нацелено на проработку среднего и переднего пучка дельтовидных мышц.',
    firstExerciseImage: '/exercises/dumbbells/DumbbellLateralRaises1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellLateralRaises2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'shoulders',
  },
  {
    id: nanoid(),
    name: 'Подъём гантелей перед собой',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Передняя дельта (10/10), средняя дельта (2/10)',
    description: 'Упражнение нацелено на проработку переднего пучка дельтовидных мышц.',
    firstExerciseImage: '/exercises/dumbbells/DumbbellFrontRaises1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellFrontRaises2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'shoulders',
  },
  {
    id: nanoid(),
    name: 'Разведение гантелей в наклоне',
    difficulty: 'Средняя сложность',
    targetMuscles: 'Задняя дельта (8/10), средняя дельта (4/10), низ трапеций (4/10)',
    description: 'Упражнение нацелено на проработку заднего пучка дельтовидных и нижней части трапецивидных мышц.',
    firstExerciseImage: '/exercises/dumbbells/DumbbellRearDeltFly1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellRearDeltFly2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'shoulders',
  },
  {
    id: nanoid(),
    name: 'Разведение гантелей в наклоне сидя',
    difficulty: 'Средняя сложность',
    targetMuscles: 'Задняя дельта (8/10), низ трапеций (4/10), средняя дельта (4/10)',
    description: 'Упражнение нацелено на проработку заднего пучка дельтовидных и нижней части трапецивидных мышц.',
    firstExerciseImage: '/exercises/dumbbells/DumbbellSeatedRearDeltFly1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellSeatedRearDeltFly2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'shoulders',
  },
  {
    id: nanoid(),
    name: 'Разведение гантелей на наклонной скамье',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Задняя дельта (8/10), низ трапеций (4/10), средняя дельта (2/10), ',
    description: 'Упражнение нацелено на проработку заднего пучка дельтовидных и нижней части трапецивидных мышц.',
    firstExerciseImage: '/exercises/dumbbells/DumbbellBenchRearDeltFly1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellBenchRearDeltFly2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'shoulders',
  },
  {
    id: nanoid(),
    name: 'Тяга гантелей на наклонной скамье',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Задняя дельта (8/10), низ трапеций (4/10), средняя дельта (2/10)',
    description: 'Упражнение нацелено на проработку заднего пучка дельтовидных мышц и нижней части трапецивидных мышц.',
    firstExerciseImage: '/exercises/dumbbells/DumbbellRearDeltRow1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellRearDeltRow2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'shoulders',
  },
  {
    id: nanoid(),
    name: 'Румынская тяга',
    difficulty: 'Средняя сложность',
    targetMuscles: 'Мышцы-разгибатели спины (9/10), задняя поверхность бедра (5/10)',
    description: 'Упражнение нацелено на проработку мышц-разгибателей спины и задней поверхности бедра',
    firstExerciseImage: '/exercises/dumbbells/DumbbellRomanianDeadlift1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellRomanianDeadlift2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'lowerback',
  },
  {
    id: nanoid(),
    name: '"С добрым утром" с гантелей в руках',
    difficulty: 'Продвинутая сложность',
    targetMuscles: 'Мышцы-разгибатели спины (8/10)',
    description: 'Упражнение нацелено на проработку мышц-разгибателей спины',
    firstExerciseImage: '/exercises/dumbbells/DumbbellGobletGoodMorning1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellGobletGoodMorning2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'lowerback',
  },
  {
    id: nanoid(),
    name: 'Приседания с гантелей в руках перед собой',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Квадрицепс (10/10), ягодицы (6/10), задняя поверхность бедра (4/10)',
    description: 'Упражнение нацелено на проработку мышц ног',
    firstExerciseImage: '/exercises/dumbbells/DumbbellGobletSquat1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellGobletSquat2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'quads',
  },
  {
    id: nanoid(),
    name: 'Приседания с гантелями',
    difficulty: 'Средняя сложность',
    targetMuscles: 'Квадрицепс (10/10), ягодицы (6/10), задняя поверхность бедра (4/10)',
    description: 'Упражнение нацелено на проработку мышц ног',
    firstExerciseImage: '/exercises/dumbbells/DumbbellSquats1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellSquats2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'quads',
  },
  {
    id: nanoid(),
    name: 'Болгарские приседания с гантелями',
    difficulty: 'Продвинутая сложность',
    targetMuscles: 'Квадрицепс (10/10), ягодицы (9/10), задняя поверхность бедра (4/10)',
    description: 'Упражнение нацелено на проработку мышц ног',
    firstExerciseImage: '/exercises/dumbbells/DumbbellBulgarianSplitSquats1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellBulgarianSplitSquats2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'quads',
  },
  {
    id: nanoid(),
    name: 'Болгарские приседания с гантелей в руках перед собой',
    difficulty: 'Продвинутая сложность',
    targetMuscles: 'Квадрицепс (10/10), ягодицы (9/10), задняя поверхность бедра (4/10)',
    description: 'Упражнение нацелено на проработку мышц ног',
    firstExerciseImage: '/exercises/dumbbells/DumbbellBulgarianGobletSquat1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellBulgarianGobletSquat2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'quads',
  },
  {
    id: nanoid(),
    name: 'Выпады с гантелями',
    difficulty: 'Средняя сложность',
    targetMuscles: 'Квадрицепс (10/10), ягодицы (4/10), задняя поверхность бедра (4/10)',
    description: 'Упражнение нацелено на проработку мышц ног',
    firstExerciseImage: '/exercises/dumbbells/DumbbellForwardLunge1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellForwardLunge2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'quads',
  },
  {
    id: nanoid(),
    name: 'Разгибания с зажатой гантелью между стопами',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Задняя поверхность бедра (9/10), квадрицепс (4/10), ягодицы (2/10), ',
    description: 'Упражнение нацелено на проработку задней поверхности бедра, а также остальных мышц ног',
    firstExerciseImage: '/exercises/dumbbells/DumbbellLegExtension1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellLegExtension2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'quads',
  },
  {
    id: nanoid(),
    name: 'Ягодичный мостик с гантелью',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Ягодицы (9/10), квадрицепс (4/10), задняя поверхность бедра (4/10), ',
    description: 'Упражнение нацелено на проработку ягодиц, а также остальных мышц ног',
    firstExerciseImage: '/exercises/dumbbells/DumbbellGluteBridge1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellGluteBridge2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'quads',
  },
  {
    id: nanoid(),
    name: 'Румынская тяга',
    difficulty: 'Средняя сложность',
    targetMuscles: 'Мышцы-разгибатели спины (9/10), задняя поверхность бедра (5/10)',
    description: 'Упражнение нацелено на проработку мышц-разгибателей спины и задней поверхности бедра',
    firstExerciseImage: '/exercises/dumbbells/DumbbellRomanianDeadlift1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellRomanianDeadlift2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'hamstrings',
  },
  {
    id: nanoid(),
    name: 'Приседания с гантелей в руках перед собой',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Квадрицепс (10/10), ягодицы (6/10), задняя поверхность бедра (4/10)',
    description: 'Упражнение нацелено на проработку мышц ног',
    firstExerciseImage: '/exercises/dumbbells/DumbbellGobletSquat1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellGobletSquat2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'hamstrings',
  },
  {
    id: nanoid(),
    name: 'Приседания с гантелями',
    difficulty: 'Средняя сложность',
    targetMuscles: 'Квадрицепс (10/10), ягодицы (6/10), задняя поверхность бедра (4/10)',
    description: 'Упражнение нацелено на проработку мышц ног',
    firstExerciseImage: '/exercises/dumbbells/DumbbellSquats1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellSquats2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'hamstrings',
  },
  {
    id: nanoid(),
    name: 'Болгарские приседания с гантелями',
    difficulty: 'Продвинутая сложность',
    targetMuscles: 'Квадрицепс (10/10), ягодицы (9/10), задняя поверхность бедра (4/10)',
    description: 'Упражнение нацелено на проработку мышц ног',
    firstExerciseImage: '/exercises/dumbbells/DumbbellBulgarianSplitSquats1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellBulgarianSplitSquats2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'hamstrings',
  },
  {
    id: nanoid(),
    name: 'Болгарские приседания с гантелей в руках перед собой',
    difficulty: 'Продвинутая сложность',
    targetMuscles: 'Квадрицепс (10/10), ягодицы (9/10), задняя поверхность бедра (4/10)',
    description: 'Упражнение нацелено на проработку мышц ног',
    firstExerciseImage: '/exercises/dumbbells/DumbbellBulgarianGobletSquat1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellBulgarianGobletSquat2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'hamstrings',
  },
  {
    id: nanoid(),
    name: 'Выпады с гантелями',
    difficulty: 'Средняя сложность',
    targetMuscles: 'Квадрицепс (10/10), ягодицы (4/10), задняя поверхность бедра (4/10)',
    description: 'Упражнение нацелено на проработку мышц ног',
    firstExerciseImage: '/exercises/dumbbells/DumbbellForwardLunge1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellForwardLunge2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'hamstrings',
  },
  {
    id: nanoid(),
    name: 'Разгибания с зажатой гантелью между стопами',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Задняя поверхность бедра (9/10), квадрицепс (4/10), ягодицы (2/10), ',
    description: 'Упражнение нацелено на проработку задней поверхности бедра, а также остальных мышц ног',
    firstExerciseImage: '/exercises/dumbbells/DumbbellLegExtension1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellLegExtension2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'hamstrings',
  },
  {
    id: nanoid(),
    name: 'Сгибания лёжа на животе с зажатой гантелью между стопами',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Задняя поверхность бедра (9/10), квадрицепс (4/10), ягодицы (4/10), ',
    description: 'Упражнение нацелено на проработку задней поверхности бедра, а также остальных мышц ног',
    firstExerciseImage: '/exercises/dumbbells/DumbbellHamstringCurl1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellHamstringCurl2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'hamstrings',
  },
  {
    id: nanoid(),
    name: 'Ягодичный мостик с гантелью',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Ягодицы (9/10), квадрицепс (4/10), задняя поверхность бедра (4/10), ',
    description: 'Упражнение нацелено на проработку ягодиц, а также остальных мышц ног',
    firstExerciseImage: '/exercises/dumbbells/DumbbellGluteBridge1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellGluteBridge2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'hamstrings',
  },
  {
    id: nanoid(),
    name: 'Ягодичный мостик с гантелью',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Ягодицы (9/10), квадрицепс (4/10), задняя поверхность бедра (4/10)',
    description: 'Упражнение нацелено на проработку ягодиц, а также остальных мышц ног',
    firstExerciseImage: '/exercises/dumbbells/DumbbellGluteBridge1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellGluteBridge2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'glutes',
  },
  {
    id: nanoid(),
    name: 'Румынская тяга',
    difficulty: 'Средняя сложность',
    targetMuscles: 'Мышцы-разгибатели спины (9/10), ягодицы (7/10), задняя поверхность бедра (4/10)',
    description: 'Упражнение нацелено на проработку мышц-разгибателей спины и задней поверхности бедра',
    firstExerciseImage: '/exercises/dumbbells/DumbbellRomanianDeadlift1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellRomanianDeadlift2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'glutes',
  },
  {
    id: nanoid(),
    name: 'Приседания с гантелей в руках перед собой',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Квадрицепс (10/10), ягодицы (6/10), задняя поверхность бедра (4/10)',
    description: 'Упражнение нацелено на проработку мышц ног',
    firstExerciseImage: '/exercises/dumbbells/DumbbellGobletSquat1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellGobletSquat2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'glutes',
  },
  {
    id: nanoid(),
    name: 'Приседания с гантелями',
    difficulty: 'Средняя сложность',
    targetMuscles: 'Квадрицепс (10/10), ягодицы (6/10), задняя поверхность бедра (4/10)',
    description: 'Упражнение нацелено на проработку мышц ног',
    firstExerciseImage: '/exercises/dumbbells/DumbbellSquats1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellSquats2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'glutes',
  },
  {
    id: nanoid(),
    name: 'Болгарские приседания с гантелями',
    difficulty: 'Продвинутая сложность',
    targetMuscles: 'Квадрицепс (10/10), ягодицы (9/10), задняя поверхность бедра (4/10)',
    description: 'Упражнение нацелено на проработку мышц ног',
    firstExerciseImage: '/exercises/dumbbells/DumbbellBulgarianSplitSquats1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellBulgarianSplitSquats2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'glutes',
  },
  {
    id: nanoid(),
    name: 'Болгарские приседания с гантелей в руках перед собой',
    difficulty: 'Продвинутая сложность',
    targetMuscles: 'Квадрицепс (10/10), ягодицы (9/10), задняя поверхность бедра (4/10)',
    description: 'Упражнение нацелено на проработку мышц ног',
    firstExerciseImage: '/exercises/dumbbells/DumbbellBulgarianGobletSquat1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellBulgarianGobletSquat2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'glutes',
  },
  {
    id: nanoid(),
    name: 'Выпады с гантелями',
    difficulty: 'Средняя сложность',
    targetMuscles: 'Квадрицепс (10/10), ягодицы (4/10), задняя поверхность бедра (4/10)',
    description: 'Упражнение нацелено на проработку мышц ног',
    firstExerciseImage: '/exercises/dumbbells/DumbbellForwardLunge1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellForwardLunge2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'glutes',
  },
  {
    id: nanoid(),
    name: 'Разгибания с зажатой гантелью между стопами',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Задняя поверхность бедра (9/10), квадрицепс (4/10), ягодицы (2/10), ',
    description: 'Упражнение нацелено на проработку задней поверхности бедра, а также остальных мышц ног',
    firstExerciseImage: '/exercises/dumbbells/DumbbellLegExtension1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellLegExtension2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'glutes',
  },
  {
    id: nanoid(),
    name: 'Сгибания лёжа на животе с зажатой гантелью между стопами',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Задняя поверхность бедра (9/10), квадрицепс (4/10), ягодицы (4/10), ',
    description: 'Упражнение нацелено на проработку задней поверхности бедра, а также остальных мышц ног',
    firstExerciseImage: '/exercises/dumbbells/DumbbellHamstringCurl1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellHamstringCurl2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'glutes',
  },
  {
    id: nanoid(),
    name: 'Подъёмы на носки с гантелями стоя',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Икроножные мышцы (10/10)',
    description: 'Упражнение нацелено на проработку икроножных мышц.',
    firstExerciseImage: '/exercises/dumbbells/DumbbellCalfRaises1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellCalfRaises2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'calves',
  },
  {
    id: nanoid(),
    name: 'Подъёмы на носки с гантелями сидя',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Икроножные мышцы (10/10)',
    description: 'Упражнение нацелено на проработку икроножных мышц.',
    firstExerciseImage: '/exercises/dumbbells/DumbbellSeatedCalfRaises1.webp',
    secondExerciseImage: '/exercises/dumbbells/DumbbellSeatedCalfRaises2.webp',
    equipmentCategory: 'dumbbells',
    bodyPartCategory: 'calves',
  },
  {
    id: nanoid(),
    name: 'Откаты штанги',
    difficulty: 'Средняя сложность',
    targetMuscles: 'Пресс (10/10)',
    description: 'Упражнение нацелено на функциональное укрепление мышц брюшного пресса.',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'barbell',
    bodyPartCategory: 'abdominals',
  },
  {
    id: nanoid(),
    name: 'Подъёмы с пола со штангой',
    difficulty: 'Средняя сложность',
    targetMuscles: 'Пресс (10/10)',
    description: 'Упражнение нацелено на функциональное укрепление мышц брюшного пресса.',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'barbell',
    bodyPartCategory: 'abdominals',
  },
  {
    id: nanoid(),
    name: 'Жим штанги на скамье',
    difficulty: 'Средняя сложность',
    targetMuscles: 'Грудь (10/10), передняя дельта (7/10).',
    description: 'Упражнение нацелено на развитие мышц груди и переднего пучках дельтовидных мышц.',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'barbell',
    bodyPartCategory: 'chest',
  },
  {
    id: nanoid(),
    name: 'Жим штанги под углом 45° на скамье',
    difficulty: 'Средняя сложность',
    targetMuscles: 'Верх груди/грудь (10/10), передняя дельта (3/10)',
    description: 'Упражнение нацелено на развитие верхней части грудных мышц.',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'barbell',
    bodyPartCategory: 'chest',
  },
  {
    id: nanoid(),
    name: 'Разгибания со штангой лёжа / "Крушитель черепов" со штангой',
    difficulty: 'Средняя сложность',
    targetMuscles: 'Трицепс (10/10)',
    description: 'Упражнение нацелено на развитие мышц трицепса.',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'barbell',
    bodyPartCategory: 'triceps',
  },
  {
    id: nanoid(),
    name: 'Разгибания штанги из-за головы',
    difficulty: 'Продвинутая сложность',
    targetMuscles: 'Трицепс (10/10)',
    description: 'Упражнение нацелено на развитие мышц трицепса.',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'barbell',
    bodyPartCategory: 'triceps',
  },
  {
    id: nanoid(),
    name: 'Супинированные сгибания штанги',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Бицепс (10/10)',
    description: 'Упражнение нацелено на проработку бицепса.',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'barbell',
    bodyPartCategory: 'biceps',
  },
  {
    id: nanoid(),
    name: 'Пронированные сгибания штанги',
    difficulty: 'Продвинутая сложность',
    targetMuscles: 'Предплечье (8/10), бицепс (5/10)',
    description: 'Упражнение нацелено на проработку мышц предплечья и бицепса.',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'barbell',
    bodyPartCategory: 'biceps',
  },
  {
    id: nanoid(),
    name: 'Тяга штанги в наклоне',
    difficulty: 'Средняя сложность',
    targetMuscles: 'Широчайшие мышцы (10/10), низ трапеций (5/10)',
    description: 'Упражнение нацелено на проработку широчайших мышц спины.',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'barbell',
    bodyPartCategory: 'lats',
  },
  {
    id: nanoid(),
    name: 'Тяга штанги с блином на одной стороне в наклоне',
    difficulty: 'Средняя сложность',
    targetMuscles: 'Широчайшие мышцы (10/10), низ трапеций (5/10)',
    description: 'Упражнение нацелено на проработку широчайших мышц спины.',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'barbell',
    bodyPartCategory: 'lats',
  },
  {
    id: nanoid(),
    name: 'Жим штанги стоя',
    difficulty: 'Средняя сложность',
    targetMuscles: 'Средняя дельта (8/10), передняя дельта (7/10), задняя дельта (4/10), трицепс (2/10)',
    description: 'Упражнение нацелено на проработку дельтовидных мышц.',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'barbell',
    bodyPartCategory: 'shoulders',
  },
  {
    id: nanoid(),
    name: 'Подъём штанги перед собой',
    difficulty: 'Средняя сложность',
    targetMuscles: 'Передняя дельта (10/10), средняя дельта (2/10)',
    description: 'Упражнение нацелено на проработку переднего пучка дельтовидных мышц.',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'barbell',
    bodyPartCategory: 'shoulders',
  },
  {
    id: nanoid(),
    name: 'Тяга штанги перед собой',
    difficulty: 'Средняя сложность',
    targetMuscles: 'Средняя дельта (10/10), верх и низ трапеций (5/10)',
    description: 'Упражнение нацелено на проработку среднего пучка дельтовидных мышц.',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'barbell',
    bodyPartCategory: 'shoulders',
  },
  {
    id: nanoid(),
    name: 'Становая тяга',
    difficulty: 'Продвинутая сложность',
    targetMuscles: 'Мышцы-разгибатели спины (9/10), ягодицы (6/10), задняя поверхность бедра (5/10)',
    description: 'Упражнение нацелено на проработку мышц-разгибателей спины, ягодиц и задней поверхности бедра',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'barbell',
    bodyPartCategory: 'lowerback',
  },
  {
    id: nanoid(),
    name: 'Румынская тяга',
    difficulty: 'Средняя сложность',
    targetMuscles: 'Мышцы-разгибатели спины (9/10), задняя поверхность бедра (5/10)',
    description: 'Упражнение нацелено на проработку мышц-разгибателей спины и задней поверхности бедра',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'barbell',
    bodyPartCategory: 'lowerback',
  },
  {
    id: nanoid(),
    name: 'Тяга-сумо',
    difficulty: 'Средняя сложность',
    targetMuscles: 'Мышцы-разгибатели спины (9/10), ягодицы (7/10), задняя поверхность бедра (5/10)',
    description: 'Упражнение нацелено на проработку мышц-разгибателей спины, ягодиц и задней поверхности бедра',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'barbell',
    bodyPartCategory: 'lowerback',
  },
  {
    id: nanoid(),
    name: '"С добрым утром" со штангой"',
    difficulty: 'Продвинутая сложность',
    targetMuscles: 'Мышцы-разгибатели спины (10/10)',
    description: 'Упражнение нацелено на проработку мышц-разгибателей спины',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'barbell',
    bodyPartCategory: 'lowerback',
  },
  {
    id: nanoid(),
    name: 'Становая тяга с обратной стороны',
    difficulty: 'Продвинутая сложность',
    targetMuscles: 'Мышцы-разгибатели спины (10/10), ягодицы (7/10), задняя поверхность бедра (5/10)',
    description: 'Упражнение нацелено на проработку мышц-разгибателей спины и мышц ног',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'barbell',
    bodyPartCategory: 'lowerback',
  },
  {
    id: nanoid(),
    name: 'Приседания со штангой',
    difficulty: 'Продвинутая сложность',
    targetMuscles: 'Квадрицепс (8/10), ягодицы (4/10), задняя поверхность бедра (7/10)',
    description: 'Упражнение нацелено на проработку мышц ног',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'barbell',
    bodyPartCategory: 'quads',
  },
  {
    id: nanoid(),
    name: 'Глубокие приседания со штангой',
    difficulty: 'Продвинутая сложность',
    targetMuscles: 'Квадрицепс (8/10), ягодицы (8/10), задняя поверхность бедра (7/10)',
    description: 'Упражнение нацелено на проработку мышц ног',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'barbell',
    bodyPartCategory: 'quads',
  },
  {
    id: nanoid(),
    name: 'Болгарские приседания со штангой',
    difficulty: 'Продвинутая сложность',
    targetMuscles: 'Квадрицепс (10/10), ягодицы (9/10), задняя поверхность бедра (4/10)',
    description: 'Упражнение нацелено на проработку мышц ног',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'barbell',
    bodyPartCategory: 'quads',
  },
  {
    id: nanoid(),
    name: 'Приседания со штангой',
    difficulty: 'Продвинутая сложность',
    targetMuscles: 'Квадрицепс (8/10), ягодицы (4/10), задняя поверхность бедра (7/10)',
    description: 'Упражнение нацелено на проработку мышц ног',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'barbell',
    bodyPartCategory: 'hamstrings',
  },
  {
    id: nanoid(),
    name: 'Глубокие приседания со штангой',
    difficulty: 'Продвинутая сложность',
    targetMuscles: 'Квадрицепс (8/10), ягодицы (8/10), задняя поверхность бедра (7/10)',
    description: 'Упражнение нацелено на проработку мышц ног',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'barbell',
    bodyPartCategory: 'hamstrings',
  },
  {
    id: nanoid(),
    name: 'Болгарские приседания со штангой',
    difficulty: 'Продвинутая сложность',
    targetMuscles: 'Квадрицепс (10/10), ягодицы (9/10), задняя поверхность бедра (4/10)',
    description: 'Упражнение нацелено на проработку мышц ног',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'barbell',
    bodyPartCategory: 'hamstrings',
  },
  {
    id: nanoid(),
    name: 'Ягодичный мостик со штангой',
    difficulty: 'Продвинутая сложность',
    targetMuscles: 'Ягодицы (9/10), квадрицепс (4/10), задняя поверхность бедра (4/10)',
    description: 'Упражнение нацелено на проработку ягодиц, а также остальных мышц ног',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'barbell',
    bodyPartCategory: 'glutes',
  },
  {
    id: nanoid(),
    name: 'Глубокие приседания со штангой',
    difficulty: 'Продвинутая сложность',
    targetMuscles: 'Квадрицепс (8/10), ягодицы (8/10), задняя поверхность бедра (7/10)',
    description: 'Упражнение нацелено на проработку мышц ног',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'barbell',
    bodyPartCategory: 'glutes',
  },
  {
    id: nanoid(),
    name: 'Подпрыгивания на носки со штангой',
    difficulty: 'Продвинутая сложность',
    targetMuscles: 'Икроножные мышцы (10/10)',
    description: 'Упражнение нацелено на проработку икроножных мышц.',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'barbell',
    bodyPartCategory: 'calves',
  },
  {
    id: nanoid(),
    name: 'Подъёмы на носки со штангой стоя',
    difficulty: 'Средняя сложность',
    targetMuscles: 'Икроножные мышцы (10/10)',
    description: 'Упражнение нацелено на проработку икроножных мышц.',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'barbell',
    bodyPartCategory: 'calves',
  },
  {
    id: nanoid(),
    name: 'Подъёмы на носки со штангой сидя',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Икроножные мышцы (10/10)',
    description: 'Упражнение нацелено на проработку икроножных мышц.',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'barbell',
    bodyPartCategory: 'calves',
  },
  {
    id: nanoid(),
    name: 'Подъёмы пятки с носками на возвышенности со штангой',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Икроножные мышцы (10/10)',
    description: 'Упражнение нацелено на проработку икроножных мышц.',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'barbell',
    bodyPartCategory: 'calves',
  },
  {
    id: nanoid(),
    name: 'Скручивания с резиновым эспандером',
    difficulty: 'Средняя сложность',
    targetMuscles: 'Пресс (10/10)',
    description: 'Упражнение нацелено на развитие мышц брюшного пресса.',
    firstExerciseImage: '/exercises/band/BandCrunches1.webp',
    secondExerciseImage: '/exercises/band/BandCrunches2.webp',
    equipmentCategory: 'band',
    bodyPartCategory: 'abdominals',
  },
  {
    id: nanoid(),
    name: 'Жим резинового эспандера одной рукой',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Грудь (8/10), передняя дельта (4/10)',
    description:
      'Упражнение нацелено на проработку мышц груди, также задействуется передняя дельта и мышцы-стабилизаторы.',
    firstExerciseImage: '/exercises/band/BandSingleArmChestPress1.webp',
    secondExerciseImage: '/exercises/band/BandSingleArmChestPress2.webp',
    equipmentCategory: 'band',
    bodyPartCategory: 'chest',
  },
  {
    id: nanoid(),
    name: 'Жим резинового эспандера двумя руками',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Грудь (8/10), передняя дельта (4/10)',
    description:
      'Упражнение нацелено на проработку мышц груди, также задействуется передняя дельта и мышцы-стабилизаторы.',
    firstExerciseImage: '/exercises/band/BandChestPress1.webp',
    secondExerciseImage: '/exercises/band/BandChestPress2.webp',
    equipmentCategory: 'band',
    bodyPartCategory: 'chest',
  },
  {
    id: nanoid(),
    name: 'Отжимания с резиновым эспандером',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Грудь (9/10), трицепс (6/10), передняя дельта (6/10)',
    description:
      'Упражнение нацелено на проработку мышц груди, также задействуется передняя дельта, мышцы-стабилизаторы и трицепс.',
    firstExerciseImage: '/exercises/band/BandPushUps1.webp',
    secondExerciseImage: '/exercises/band/BandPushUps2.webp',
    equipmentCategory: 'band',
    bodyPartCategory: 'chest',
  },
  {
    id: nanoid(),
    name: 'Приведения одной рукой с резиновым эспандером',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Грудь (9/10)',
    description: 'Упражнение нацелено на растяжку и развитие грудных мышц.',
    firstExerciseImage: '/exercises/band/BandSingleArmPecFly1.webp',
    secondExerciseImage: '/exercises/band/BandSingleArmPecFly2.webp',
    equipmentCategory: 'band',
    bodyPartCategory: 'chest',
  },
  {
    id: nanoid(),
    name: 'Приведения двумя руками с резиновым эспандером',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Грудь (9/10)',
    description: 'Упражнение нацелено на растяжку и развитие грудных мышц.',
    firstExerciseImage: '/exercises/band/BandChestFly1.webp',
    secondExerciseImage: '/exercises/band/BandChestFly2.webp',
    equipmentCategory: 'band',
    bodyPartCategory: 'chest',
  },
  {
    id: nanoid(),
    name: 'Разгибания с резиновым эспандером',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Трицепс (10/10)',
    description: 'Упражнение нацелено на проработку трицепса.',
    firstExerciseImage: '/exercises/band/BandPushdown1.webp',
    secondExerciseImage: '/exercises/band/BandPushdown2.webp',
    equipmentCategory: 'band',
    bodyPartCategory: 'triceps',
  },
  {
    id: nanoid(),
    name: 'Разгибания с резиновым эспандером из-за головы',
    difficulty: 'Продвинутая сложность',
    targetMuscles: 'Трицепс (10/10)',
    description: 'Упражнение нацелено на проработку трицепса.',
    firstExerciseImage: '/exercises/band/BandSkullcrusher1.webp',
    secondExerciseImage: '/exercises/band/BandSkullcrusher2.webp',
    equipmentCategory: 'band',
    bodyPartCategory: 'triceps',
  },
  {
    id: nanoid(),
    name: 'Разгибания с резиновым эспандером из-за головы по центру',
    difficulty: 'Продвинутая сложность',
    targetMuscles: 'Трицепс (10/10)',
    description: 'Упражнение нацелено на проработку трицепса.',
    firstExerciseImage: '/exercises/band/BandOverheadExtension1.webp',
    secondExerciseImage: '/exercises/band/BandOverheadExtension2.webp',
    equipmentCategory: 'band',
    bodyPartCategory: 'triceps',
  },
  {
    id: nanoid(),
    name: 'Супинированные сгибания с резиновым эспандером',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Бицепс (10/10)',
    description: 'Упражнение нацелено на проработку бицепса.',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'band',
    bodyPartCategory: 'biceps',
  },
  {
    id: nanoid(),
    name: 'Пронированные сгибания с резиновым эспандером',
    difficulty: 'Средняя сложность',
    targetMuscles: 'Предплечья (8/10), бицепс (4/10)',
    description: 'Упражнение нацелено на проработку предплечий и бицепса.',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'band',
    bodyPartCategory: 'biceps',
  },
  {
    id: nanoid(),
    name: 'Тяга резинового эспандера в наклоне',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Широчайшие мышцы (10/10), низ трапеций (5/10)',
    description: 'Упражнение нацелено на проработку широчайших мышц спины.',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'band',
    bodyPartCategory: 'lats',
  },
  {
    id: nanoid(),
    name: 'Пуловер с резиновым эспандером',
    difficulty: 'Средняя сложность',
    targetMuscles: 'Широчайшие мышцы (10/10), низ трапеций (5/10)',
    description: 'Упражнение нацелено на растяжку и развитие широчайших мышц спины.',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'band',
    bodyPartCategory: 'lats',
  },
  {
    id: nanoid(),
    name: 'Тяга резинового эспандера одной рукой',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Широчайшие мышцы (10/10), низ трапеций (5/10)',
    description: 'Упражнение нацелено на проработку широчайших мышц спины.',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'band',
    bodyPartCategory: 'lats',
  },
  {
    id: nanoid(),
    name: 'Растягивание резинового эспандера',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Заполнить позже',
    description: 'Заполнить позже',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'band',
    bodyPartCategory: 'shoulders',
  },
  {
    id: nanoid(),
    name: 'Жим резинового эспандера стоя',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Заполнить позже',
    description: 'Заполнить позже',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'band',
    bodyPartCategory: 'shoulders',
  },
  {
    id: nanoid(),
    name: 'Тяга резинового эспандера к лицу',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Заполнить позже',
    description: 'Заполнить позже',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'band',
    bodyPartCategory: 'shoulders',
  },
  {
    id: nanoid(),
    name: 'Разведение резинового эспандера в стороны',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Заполнить позже',
    description: 'Заполнить позже',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'band',
    bodyPartCategory: 'shoulders',
  },
  {
    id: nanoid(),
    name: 'Разведение резинового эспандера в стороны одной рукой',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Заполнить позже',
    description: 'Заполнить позже',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'band',
    bodyPartCategory: 'shoulders',
  },
  {
    id: nanoid(),
    name: 'Тяга резинового эспандера перед собой',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Заполнить позже',
    description: 'Заполнить позже',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'band',
    bodyPartCategory: 'shoulders',
  },
  {
    id: nanoid(),
    name: 'Румынская тяга с резиновым эспандером',
    difficulty: 'Средняя сложность',
    targetMuscles: 'Мышцы-разгибатели спины (9/10), задняя поверхность бедра (5/10)',
    description: 'Упражнение нацелено на проработку мышц-разгибателей спины и задней поверхности бедра',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'band',
    bodyPartCategory: 'lowerback',
  },
  {
    id: nanoid(),
    name: '"С добрым утром" с резиновым эспандером',
    difficulty: 'Средняя сложность',
    targetMuscles: 'Мышцы-разгибатели спины (9/10), задняя поверхность бедра (5/10)',
    description: 'Упражнение нацелено на проработку мышц-разгибателей спины и задней поверхности бедра',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'band',
    bodyPartCategory: 'lowerback',
  },
  {
    id: nanoid(),
    name: 'Толчки с резиновым эспандером',
    difficulty: 'Средняя сложность',
    targetMuscles: 'Мышцы-разгибатели спины (9/10), задняя поверхность бедра (5/10)',
    description: 'Упражнение нацелено на проработку мышц-разгибателей спины и задней поверхности бедра',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'band',
    bodyPartCategory: 'lowerback',
  },
  {
    id: nanoid(),
    name: 'Приседания с резиновым эспандером',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Квадрицепс (8/10), ягодицы (4/10), задняя поверхность бедра (7/10)',
    description: 'Упражнение нацелено на проработку мышц ног',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'band',
    bodyPartCategory: 'quads',
  },
  {
    id: nanoid(),
    name: 'Разгибания ног с резиновым эспандером',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Квадрицепс (8/10), ягодицы (4/10), задняя поверхность бедра (7/10)',
    description: 'Упражнение нацелено на проработку мышц ног',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'band',
    bodyPartCategory: 'quads',
  },
  {
    id: nanoid(),
    name: 'Румынская тяга с резиновым эспандером',
    difficulty: 'Средняя сложность',
    targetMuscles: 'Мышцы-разгибатели спины (9/10), задняя поверхность бедра (5/10)',
    description: 'Упражнение нацелено на проработку мышц-разгибателей спины и задней поверхности бедра',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'band',
    bodyPartCategory: 'hamstrings',
  },
  {
    id: nanoid(),
    name: '"С добрым утром" с резиновым эспандером',
    difficulty: 'Средняя сложность',
    targetMuscles: 'Мышцы-разгибатели спины (9/10), задняя поверхность бедра (5/10)',
    description: 'Упражнение нацелено на проработку мышц-разгибателей спины и задней поверхности бедра',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'band',
    bodyPartCategory: 'hamstrings',
  },
  {
    id: nanoid(),
    name: 'Сгибания резинового эспандера лёжа на животе',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Задняя поверхность бедра (9/10), квадрицепс (4/10), ягодицы (4/10), ',
    description: 'Упражнение нацелено на проработку задней поверхности бедра, а также остальных мышц ног',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'band',
    bodyPartCategory: 'hamstrings',
  },
  {
    id: nanoid(),
    name: 'Румынская тяга с резиновым эспандером',
    difficulty: 'Средняя сложность',
    targetMuscles: 'Мышцы-разгибатели спины (9/10), задняя поверхность бедра (5/10)',
    description: 'Упражнение нацелено на проработку мышц-разгибателей спины и задней поверхности бедра',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'band',
    bodyPartCategory: 'glutes',
  },
  {
    id: nanoid(),
    name: 'Приседания с резиновым эспандером',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Квадрицепс (8/10), ягодицы (4/10), задняя поверхность бедра (7/10)',
    description: 'Упражнение нацелено на проработку мышц ног',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'band',
    bodyPartCategory: 'glutes',
  },
  {
    id: nanoid(),
    name: 'Отведения ноги назад с резиновым эспандером',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Ягодицы (8/10), задняя поверхность бедра (7/10), квадрицепс (4/10)',
    description: 'Упражнение нацелено на проработку мышц ног',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'band',
    bodyPartCategory: 'glutes',
  },
  {
    id: nanoid(),
    name: 'Отведения ноги с резиновым эспандером',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Ягодицы (8/10), задняя поверхность бедра (7/10)',
    description: 'Упражнение нацелено на проработку ягодиц',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'band',
    bodyPartCategory: 'glutes',
  },
  {
    id: nanoid(),
    name: 'Подъём на носки с резиновым эспандером',
    difficulty: 'Начальная сложность',
    targetMuscles: 'Икроножные мышцы (10/10)',
    description: 'Упражнение нацелено на проработку икроножных мышц.',
    firstExerciseImage: '',
    secondExerciseImage: '',
    equipmentCategory: 'band',
    bodyPartCategory: 'calves',
  },
]
